// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUSUZ9Lj-TKuqZRrGaTKsvj_Y6fUdmqoM',
    appId: '1:248502364521:web:ffc76e55497841360e35f8',
    messagingSenderId: '248502364521',
    projectId: 'chalkman-5a4e0',
    authDomain: 'chalkman-5a4e0.firebaseapp.com',
    storageBucket: 'chalkman-5a4e0.firebasestorage.app',
    measurementId: 'G-PF2XBP15XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqwuHzLqwc4cFOqU2qM0Mv74gBjWTVe0',
    appId: '1:248502364521:android:8c207002e319155d0e35f8',
    messagingSenderId: '248502364521',
    projectId: 'chalkman-5a4e0',
    storageBucket: 'chalkman-5a4e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBpw1cvSDOqXEC6fd6eKJyQVtozkQPv0',
    appId: '1:248502364521:ios:fd5fee9607e27b250e35f8',
    messagingSenderId: '248502364521',
    projectId: 'chalkman-5a4e0',
    storageBucket: 'chalkman-5a4e0.firebasestorage.app',
    iosBundleId: 'com.pooltableke.pooltableKe',
  );
}
